---
matrix:
  include:
  - name: "Succinct Unit Tests"
    language: swift
    os: osx
    osx_image: xcode12.2
    xcode_project: Succinct.xcodeproj
    xcode_scheme: Succinct
    xcode_destination: platform=iOS Simulator,OS=latest,name=iPhone 11

  - name: "Succinct Simulator Tests"
    language: swift
    os: osx
    osx_image: xcode12.2
    xcode_project: Succinct.xcodeproj
    xcode_scheme: SuccinctContainer
    xcode_destination: platform=iOS Simulator,OS=latest,name=iPhone 11

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bundle install
  - make documentation

after_failure:
  - cat $TMPDIR/carthage-*.log

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  local_dir: docs
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
